### PR TITLE
Update HTMLang.js

### PR DESCRIPTION
**Pull request by Justiniscoding**
Make print Be Able to print more then one tag

### CODE REVIEW

**Comment by rexim** [comment]
What print?

**Comment by Justiniscoding** [comment]
you can now use&lt;print>&lt;s>Hello,&lt;/s>&lt;s>World&lt;/s>&lt;/print> this was not supported earlier

**Comment by Justiniscoding** [comment]
<print>

**Comment by Justiniscoding** [comment]
i forgot that you added the new call function

**Pull request closed without merging**
